[2025-03-01T01:41:23.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T01:41:23.827+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_postgres_1.generate_and_insert_orders manual__2025-03-01T01:41:18.217940+00:00 [queued]>
[2025-03-01T01:41:23.835+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_postgres_1.generate_and_insert_orders manual__2025-03-01T01:41:18.217940+00:00 [queued]>
[2025-03-01T01:41:23.835+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T01:41:23.848+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_and_insert_orders> on 2025-03-01 01:41:18.217940+00:00
[2025-03-01T01:41:23.858+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=42140) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T01:41:23.858+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_1', 'generate_and_insert_orders', 'manual__2025-03-01T01:41:18.217940+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_generate_table_info.py', '--cfg-path', '/tmp/tmpgg0wrwga']
[2025-03-01T01:41:23.859+0000] {standard_task_runner.py:72} INFO - Started process 42151 to run task
[2025-03-01T01:41:23.859+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask generate_and_insert_orders
[2025-03-01T01:41:23.896+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_postgres_1.generate_and_insert_orders manual__2025-03-01T01:41:18.217940+00:00 [running]> on host e6b43e607126
[2025-03-01T01:41:23.967+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='kucikm23@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_postgres_1' AIRFLOW_CTX_TASK_ID='generate_and_insert_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T01:41:18.217940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T01:41:18.217940+00:00'
[2025-03-01T01:41:23.968+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-01T01:41:23.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-01T01:41:23.969+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_insert_orders state:running start_date:2025-03-01 01:41:23.828124+00:00
[2025-03-01T01:41:23.969+0000] {logging_mixin.py:190} INFO - Dag name:dag_postgres_1 and current dag run status:running
[2025-03-01T01:41:23.970+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T01:41:24.067+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-03-01T01:41:28.186+0000] {sql.py:639} INFO - Loaded 5000 rows into orders so far
[2025-03-01T01:41:33.394+0000] {sql.py:639} INFO - Loaded 5000 rows into orders so far
[2025-03-01T01:41:33.395+0000] {sql.py:652} INFO - Done loading. Loaded a total of 10000 rows into orders
[2025-03-01T01:41:33.399+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-01T01:41:33.412+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T01:41:33.413+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_postgres_1, task_id=generate_and_insert_orders, run_id=manual__2025-03-01T01:41:18.217940+00:00, execution_date=20250301T014118, start_date=20250301T014123, end_date=20250301T014133
[2025-03-01T01:41:33.449+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-01T01:41:33.450+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-01T01:41:33.450+0000] {logging_mixin.py:190} INFO - Dag name:dag_postgres_1 queued_at:2025-03-01 01:41:18.228427+00:00
[2025-03-01T01:41:33.451+0000] {logging_mixin.py:190} INFO - Task hostname:e6b43e607126 operator:PythonOperator
[2025-03-01T01:41:33.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-01T01:41:33.483+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T01:41:33.488+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
